### ISSUE TITLE
Seeking clarification for `ssp` argument `--thre_pb`

### ISSUE THREAD

**Issue by kalavattam** [rnakato/SSP#3]
Dear @rnakato,

Thank you to you and your lab personnel for making and maintaining this great tool. I am writing to seek clarification for the argument `--thre_pb`. In the `--help` documentation, `--thre_pb` is described as follows:
```txt
  --thre_pb arg (=0)           PCRbias threshold (default: more than max(1 read, 10 times greater
                               than genome average))
```

- If I want to adjust the threshold for alignment redundancy, is this the argument I should use? For example, if I want any read alignments above threshold $T = 1$ to be considered redundant duplicates, should I invoke `ssp` with the argument `--thre_pb 1`?
- Additionally, is the default value for `--thre_pb` zero (from "`(=0)`") or "`more than max(1 read, 10 times greater than genome average)`"? If it is the latter, then does this mean the threshold for redundancy $T$ is set to $10 \times \(\text{mean number of duplicate alignments genome wide}\)$? I don't understand what the description means.

I'll appreciate any help and guidance you can provide. Thank you.

–Kris

**Comment by rnakato** [comment]
Hi Kris,

Thanks for your question, and I'm sorry for the lack of explanation about the option.
- The default value of `--thre_pb` is zero, where **ssp** uses the redundancy threshold `> max(1 read, 10 times greater than genome average)`. Because `10 times greater than genome average` often becomes <1 in the large genome (e.g. human and mouse), the threshold T is in most cases 1. For small genomes (e.g. yeast), `10 times greater than genome average` often becomes 4 or 5, so this value is used. **ssp** outputs the threshold used in the log like: `Checking redundant reads: redundancy threshold 4`

- If the user specifies the `--thre_pb` option, `10 times greater than genome average` is ignored and **ssp** uses the specified threshold. For example, if you set `--thre_pb 1` for the yeast sample, **ssp** will use T=1, which means that at most one read mapped to each position will be non-redundant and the other reads will be filtered. 

Feel free to ask a question if something is still unclear.

**Comment by kalavattam** [comment]
Thank you for the kind, clear, and careful explanation. I understand. Thank you again for making and maintaining these great tools!
